[package]
name = "zerostash-fuse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
infinitree = { version = "0.10.2", features = ["cryptobox", "yubikey"] }
zerostash-files = { version = "0.6.0", path = "../zerostash-files" }
scc = "1.8.2"
fuse_mt = "0.6.0"
tracing = "0.1.37"
nix = { version = "0.26.2", default-features = false, features = ["user"] }
anyhow = "1.0.71"
tokio = { version = "1.28.2", features = ["rt", "time", "signal", "rt-multi-thread"] }

[dev-dependencies]
criterion = "0.3.6"

[[bench]]
name = "fuse_bench"
harness = false
path = "benches/bench.rs"
