[package]
name = "libzerostash"
version = "0.1.0"
authors = ["Peter Parkanyi <me@rhapsodhy.hu>"]
repository = "https://github.com/rsdy/zerostash"
license = "GPL-3.0"
build = "build.rs"
edition= "2018"

[dependencies]
glob = { version = "0.3" }
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_cbor = "^0.10.1"
walkdir = "^2.2.7"
parking_lot = { version = "^0.10" } 
crossbeam-channel = "^0.3"
crossbeam-utils = "^0.6.6"
memmap = "0.7"
blake2 = { version = "0.8", features = ["simd"] }
failure = "0.1"
lz4 = "^1.23.1"
ring = "^0.16"
itertools = "0.8"
seahash = "3.0"
libsodium-sys-stable = "1.18.2"
libc = "0.2"
zeroize = "1.0"
lru = "0.4"

[dev-dependencies]